# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c4a4540ccc9d17fe340837ad882fcba59b1fd3719e6298868437becea94feba6b3fbeaa0227e2be5e0e9aa123cdfbd852e311ed50cb7593964a263fa0bbd971

test:
  secret_key_base: 62a6b0693f79db3e6cd011076183917d8fb45c79423f4eb63c26d2ec909c5c48ca1b600c2479be50850ec4336effd06f1e695a778348e7d13ef1620df7c784ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
